/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables.records;


import com.q3js.jooq.tables.Servers;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServersRecord extends UpdatableRecordImpl<ServersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>servers.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>servers.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>servers.host</code>.
     */
    public void setHost(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>servers.host</code>.
     */
    public String getHost() {
        return (String) get(1);
    }

    /**
     * Setter for <code>servers.proxy_port</code>.
     */
    public void setProxyPort(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>servers.proxy_port</code>.
     */
    public Integer getProxyPort() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>servers.target_host</code>.
     */
    public void setTargetHost(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>servers.target_host</code>.
     */
    public String getTargetHost() {
        return (String) get(3);
    }

    /**
     * Setter for <code>servers.target_port</code>.
     */
    public void setTargetPort(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>servers.target_port</code>.
     */
    public Integer getTargetPort() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>servers.secure</code>.
     */
    public void setSecure(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>servers.secure</code>.
     */
    public Boolean getSecure() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>servers.fs_game</code>.
     */
    public void setFsGame(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>servers.fs_game</code>.
     */
    public String getFsGame() {
        return (String) get(6);
    }

    /**
     * Setter for <code>servers.permanent</code>.
     */
    public void setPermanent(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>servers.permanent</code>.
     */
    public Boolean getPermanent() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>servers.display_order</code>.
     */
    public void setDisplayOrder(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>servers.display_order</code>.
     */
    public Integer getDisplayOrder() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>servers.last_heartbeat_at</code>.
     */
    public void setLastHeartbeatAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>servers.last_heartbeat_at</code>.
     */
    public OffsetDateTime getLastHeartbeatAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>servers.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>servers.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>servers.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>servers.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServersRecord
     */
    public ServersRecord() {
        super(Servers.SERVERS);
    }

    /**
     * Create a detached, initialised ServersRecord
     */
    public ServersRecord(Long id, String host, Integer proxyPort, String targetHost, Integer targetPort, Boolean secure, String fsGame, Boolean permanent, Integer displayOrder, OffsetDateTime lastHeartbeatAt, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Servers.SERVERS);

        setId(id);
        setHost(host);
        setProxyPort(proxyPort);
        setTargetHost(targetHost);
        setTargetPort(targetPort);
        setSecure(secure);
        setFsGame(fsGame);
        setPermanent(permanent);
        setDisplayOrder(displayOrder);
        setLastHeartbeatAt(lastHeartbeatAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ServersRecord
     */
    public ServersRecord(com.q3js.jooq.tables.pojos.Servers value) {
        super(Servers.SERVERS);

        if (value != null) {
            setId(value.getId());
            setHost(value.getHost());
            setProxyPort(value.getProxyPort());
            setTargetHost(value.getTargetHost());
            setTargetPort(value.getTargetPort());
            setSecure(value.getSecure());
            setFsGame(value.getFsGame());
            setPermanent(value.getPermanent());
            setDisplayOrder(value.getDisplayOrder());
            setLastHeartbeatAt(value.getLastHeartbeatAt());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
