/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/game'
import { Route as withLayoutRouteRouteImport } from './routes/(withLayout)/route'
import { Route as withLayoutIndexRouteImport } from './routes/(withLayout)/index'
import { Route as withLayoutScoreboardRouteImport } from './routes/(withLayout)/scoreboard'
import { Route as withLayoutGuideRouteImport } from './routes/(withLayout)/guide'

const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const withLayoutRouteRoute = withLayoutRouteRouteImport.update({
  id: '/(withLayout)',
  getParentRoute: () => rootRouteImport,
} as any)
const withLayoutIndexRoute = withLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => withLayoutRouteRoute,
} as any)
const withLayoutScoreboardRoute = withLayoutScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => withLayoutRouteRoute,
} as any)
const withLayoutGuideRoute = withLayoutGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => withLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/game': typeof GameRoute
  '/guide': typeof withLayoutGuideRoute
  '/scoreboard': typeof withLayoutScoreboardRoute
  '/': typeof withLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/game': typeof GameRoute
  '/guide': typeof withLayoutGuideRoute
  '/scoreboard': typeof withLayoutScoreboardRoute
  '/': typeof withLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(withLayout)': typeof withLayoutRouteRouteWithChildren
  '/game': typeof GameRoute
  '/(withLayout)/guide': typeof withLayoutGuideRoute
  '/(withLayout)/scoreboard': typeof withLayoutScoreboardRoute
  '/(withLayout)/': typeof withLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/game' | '/guide' | '/scoreboard' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/game' | '/guide' | '/scoreboard' | '/'
  id:
    | '__root__'
    | '/(withLayout)'
    | '/game'
    | '/(withLayout)/guide'
    | '/(withLayout)/scoreboard'
    | '/(withLayout)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  withLayoutRouteRoute: typeof withLayoutRouteRouteWithChildren
  GameRoute: typeof GameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(withLayout)': {
      id: '/(withLayout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof withLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(withLayout)/': {
      id: '/(withLayout)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof withLayoutIndexRouteImport
      parentRoute: typeof withLayoutRouteRoute
    }
    '/(withLayout)/scoreboard': {
      id: '/(withLayout)/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof withLayoutScoreboardRouteImport
      parentRoute: typeof withLayoutRouteRoute
    }
    '/(withLayout)/guide': {
      id: '/(withLayout)/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof withLayoutGuideRouteImport
      parentRoute: typeof withLayoutRouteRoute
    }
  }
}

interface withLayoutRouteRouteChildren {
  withLayoutGuideRoute: typeof withLayoutGuideRoute
  withLayoutScoreboardRoute: typeof withLayoutScoreboardRoute
  withLayoutIndexRoute: typeof withLayoutIndexRoute
}

const withLayoutRouteRouteChildren: withLayoutRouteRouteChildren = {
  withLayoutGuideRoute: withLayoutGuideRoute,
  withLayoutScoreboardRoute: withLayoutScoreboardRoute,
  withLayoutIndexRoute: withLayoutIndexRoute,
}

const withLayoutRouteRouteWithChildren = withLayoutRouteRoute._addFileChildren(
  withLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  withLayoutRouteRoute: withLayoutRouteRouteWithChildren,
  GameRoute: GameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
