/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables;


import com.q3js.jooq.DefaultSchema;
import com.q3js.jooq.Indexes;
import com.q3js.jooq.Keys;
import com.q3js.jooq.tables.records.ServersRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Servers extends TableImpl<ServersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>servers</code>
     */
    public static final Servers SERVERS = new Servers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServersRecord> getRecordType() {
        return ServersRecord.class;
    }

    /**
     * The column <code>servers.id</code>.
     */
    public final TableField<ServersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>servers.host</code>.
     */
    public final TableField<ServersRecord, String> HOST = createField(DSL.name("host"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>servers.proxy_port</code>.
     */
    public final TableField<ServersRecord, Integer> PROXY_PORT = createField(DSL.name("proxy_port"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>servers.target_host</code>.
     */
    public final TableField<ServersRecord, String> TARGET_HOST = createField(DSL.name("target_host"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>servers.target_port</code>.
     */
    public final TableField<ServersRecord, Integer> TARGET_PORT = createField(DSL.name("target_port"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>servers.secure</code>.
     */
    public final TableField<ServersRecord, Boolean> SECURE = createField(DSL.name("secure"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>servers.fs_game</code>.
     */
    public final TableField<ServersRecord, String> FS_GAME = createField(DSL.name("fs_game"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>servers.permanent</code>.
     */
    public final TableField<ServersRecord, Boolean> PERMANENT = createField(DSL.name("permanent"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>servers.display_order</code>.
     */
    public final TableField<ServersRecord, Integer> DISPLAY_ORDER = createField(DSL.name("display_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>servers.last_heartbeat_at</code>.
     */
    public final TableField<ServersRecord, OffsetDateTime> LAST_HEARTBEAT_AT = createField(DSL.name("last_heartbeat_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>servers.created_at</code>.
     */
    public final TableField<ServersRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>servers.updated_at</code>.
     */
    public final TableField<ServersRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Servers(Name alias, Table<ServersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Servers(Name alias, Table<ServersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>servers</code> table reference
     */
    public Servers(String alias) {
        this(DSL.name(alias), SERVERS);
    }

    /**
     * Create an aliased <code>servers</code> table reference
     */
    public Servers(Name alias) {
        this(alias, SERVERS);
    }

    /**
     * Create a <code>servers</code> table reference
     */
    public Servers() {
        this(DSL.name("servers"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SERVERS_DISPLAY_ORDER, Indexes.IDX_SERVERS_LAST_HEARTBEAT_AT);
    }

    @Override
    public Identity<ServersRecord, Long> getIdentity() {
        return (Identity<ServersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServersRecord> getPrimaryKey() {
        return Keys.SERVERS_PKEY;
    }

    @Override
    public List<UniqueKey<ServersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_SERVERS_HOST_PROXY_TARGET);
    }

    @Override
    public List<Check<ServersRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("servers_proxy_port_check"), "(((proxy_port >= 1) AND (proxy_port <= 65535)))", true),
            Internal.createCheck(this, DSL.name("servers_target_port_check"), "(((target_port >= 1) AND (target_port <= 65535)))", true)
        );
    }

    @Override
    public Servers as(String alias) {
        return new Servers(DSL.name(alias), this);
    }

    @Override
    public Servers as(Name alias) {
        return new Servers(alias, this);
    }

    @Override
    public Servers as(Table<?> alias) {
        return new Servers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Servers rename(String name) {
        return new Servers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servers rename(Name name) {
        return new Servers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servers rename(Table<?> name) {
        return new Servers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servers where(Condition condition) {
        return new Servers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
