/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Servers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String host;
    private Integer proxyPort;
    private String targetHost;
    private Integer targetPort;
    private Boolean secure;
    private String fsGame;
    private Boolean permanent;
    private Integer displayOrder;
    private OffsetDateTime lastHeartbeatAt;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public Servers() {}

    public Servers(Servers value) {
        this.id = value.id;
        this.host = value.host;
        this.proxyPort = value.proxyPort;
        this.targetHost = value.targetHost;
        this.targetPort = value.targetPort;
        this.secure = value.secure;
        this.fsGame = value.fsGame;
        this.permanent = value.permanent;
        this.displayOrder = value.displayOrder;
        this.lastHeartbeatAt = value.lastHeartbeatAt;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Servers(
        Long id,
        String host,
        Integer proxyPort,
        String targetHost,
        Integer targetPort,
        Boolean secure,
        String fsGame,
        Boolean permanent,
        Integer displayOrder,
        OffsetDateTime lastHeartbeatAt,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.host = host;
        this.proxyPort = proxyPort;
        this.targetHost = targetHost;
        this.targetPort = targetPort;
        this.secure = secure;
        this.fsGame = fsGame;
        this.permanent = permanent;
        this.displayOrder = displayOrder;
        this.lastHeartbeatAt = lastHeartbeatAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>servers.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>servers.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>servers.host</code>.
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Setter for <code>servers.host</code>.
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Getter for <code>servers.proxy_port</code>.
     */
    public Integer getProxyPort() {
        return this.proxyPort;
    }

    /**
     * Setter for <code>servers.proxy_port</code>.
     */
    public void setProxyPort(Integer proxyPort) {
        this.proxyPort = proxyPort;
    }

    /**
     * Getter for <code>servers.target_host</code>.
     */
    public String getTargetHost() {
        return this.targetHost;
    }

    /**
     * Setter for <code>servers.target_host</code>.
     */
    public void setTargetHost(String targetHost) {
        this.targetHost = targetHost;
    }

    /**
     * Getter for <code>servers.target_port</code>.
     */
    public Integer getTargetPort() {
        return this.targetPort;
    }

    /**
     * Setter for <code>servers.target_port</code>.
     */
    public void setTargetPort(Integer targetPort) {
        this.targetPort = targetPort;
    }

    /**
     * Getter for <code>servers.secure</code>.
     */
    public Boolean getSecure() {
        return this.secure;
    }

    /**
     * Setter for <code>servers.secure</code>.
     */
    public void setSecure(Boolean secure) {
        this.secure = secure;
    }

    /**
     * Getter for <code>servers.fs_game</code>.
     */
    public String getFsGame() {
        return this.fsGame;
    }

    /**
     * Setter for <code>servers.fs_game</code>.
     */
    public void setFsGame(String fsGame) {
        this.fsGame = fsGame;
    }

    /**
     * Getter for <code>servers.permanent</code>.
     */
    public Boolean getPermanent() {
        return this.permanent;
    }

    /**
     * Setter for <code>servers.permanent</code>.
     */
    public void setPermanent(Boolean permanent) {
        this.permanent = permanent;
    }

    /**
     * Getter for <code>servers.display_order</code>.
     */
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    /**
     * Setter for <code>servers.display_order</code>.
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * Getter for <code>servers.last_heartbeat_at</code>.
     */
    public OffsetDateTime getLastHeartbeatAt() {
        return this.lastHeartbeatAt;
    }

    /**
     * Setter for <code>servers.last_heartbeat_at</code>.
     */
    public void setLastHeartbeatAt(OffsetDateTime lastHeartbeatAt) {
        this.lastHeartbeatAt = lastHeartbeatAt;
    }

    /**
     * Getter for <code>servers.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>servers.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>servers.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>servers.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Servers other = (Servers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.host == null) {
            if (other.host != null)
                return false;
        }
        else if (!this.host.equals(other.host))
            return false;
        if (this.proxyPort == null) {
            if (other.proxyPort != null)
                return false;
        }
        else if (!this.proxyPort.equals(other.proxyPort))
            return false;
        if (this.targetHost == null) {
            if (other.targetHost != null)
                return false;
        }
        else if (!this.targetHost.equals(other.targetHost))
            return false;
        if (this.targetPort == null) {
            if (other.targetPort != null)
                return false;
        }
        else if (!this.targetPort.equals(other.targetPort))
            return false;
        if (this.secure == null) {
            if (other.secure != null)
                return false;
        }
        else if (!this.secure.equals(other.secure))
            return false;
        if (this.fsGame == null) {
            if (other.fsGame != null)
                return false;
        }
        else if (!this.fsGame.equals(other.fsGame))
            return false;
        if (this.permanent == null) {
            if (other.permanent != null)
                return false;
        }
        else if (!this.permanent.equals(other.permanent))
            return false;
        if (this.displayOrder == null) {
            if (other.displayOrder != null)
                return false;
        }
        else if (!this.displayOrder.equals(other.displayOrder))
            return false;
        if (this.lastHeartbeatAt == null) {
            if (other.lastHeartbeatAt != null)
                return false;
        }
        else if (!this.lastHeartbeatAt.equals(other.lastHeartbeatAt))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.host == null) ? 0 : this.host.hashCode());
        result = prime * result + ((this.proxyPort == null) ? 0 : this.proxyPort.hashCode());
        result = prime * result + ((this.targetHost == null) ? 0 : this.targetHost.hashCode());
        result = prime * result + ((this.targetPort == null) ? 0 : this.targetPort.hashCode());
        result = prime * result + ((this.secure == null) ? 0 : this.secure.hashCode());
        result = prime * result + ((this.fsGame == null) ? 0 : this.fsGame.hashCode());
        result = prime * result + ((this.permanent == null) ? 0 : this.permanent.hashCode());
        result = prime * result + ((this.displayOrder == null) ? 0 : this.displayOrder.hashCode());
        result = prime * result + ((this.lastHeartbeatAt == null) ? 0 : this.lastHeartbeatAt.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Servers (");

        sb.append(id);
        sb.append(", ").append(host);
        sb.append(", ").append(proxyPort);
        sb.append(", ").append(targetHost);
        sb.append(", ").append(targetPort);
        sb.append(", ").append(secure);
        sb.append(", ").append(fsGame);
        sb.append(", ").append(permanent);
        sb.append(", ").append(displayOrder);
        sb.append(", ").append(lastHeartbeatAt);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
