// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import { getAllServersResponseTransformer, getPlayerStatsResponseTransformer } from './transformers.gen';
import type { GetAllPlayersData, GetAllPlayersResponses, GetAllServersData, GetAllServersResponses, GetGlobalScoreboardData, GetGlobalScoreboardResponses, GetKillDistributionData, GetKillDistributionResponses, GetPlayerStatsData, GetPlayerStatsResponses, GetServerInfoData, GetServerInfoResponses, IngestEventData, IngestEventErrors, IngestEventResponses, RefreshServerData, RefreshServerErrors, RefreshServerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Ingest Event
 */
export const ingestEvent = <ThrowOnError extends boolean = false>(options: Options<IngestEventData, ThrowOnError>) => (options.client ?? client).post<IngestEventResponses, IngestEventErrors, ThrowOnError>({
    url: '/api/events',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Kill Distribution
 */
export const getKillDistribution = <ThrowOnError extends boolean = false>(options?: Options<GetKillDistributionData, ThrowOnError>) => (options?.client ?? client).get<GetKillDistributionResponses, unknown, ThrowOnError>({ url: '/api/events/distribution', ...options });

/**
 * Get Global Scoreboard
 */
export const getGlobalScoreboard = <ThrowOnError extends boolean = false>(options?: Options<GetGlobalScoreboardData, ThrowOnError>) => (options?.client ?? client).get<GetGlobalScoreboardResponses, unknown, ThrowOnError>({ url: '/api/events/scoreboard', ...options });

/**
 * Get All Players
 */
export const getAllPlayers = <ThrowOnError extends boolean = false>(options?: Options<GetAllPlayersData, ThrowOnError>) => (options?.client ?? client).get<GetAllPlayersResponses, unknown, ThrowOnError>({ url: '/api/players', ...options });

/**
 * Get Player Stats
 */
export const getPlayerStats = <ThrowOnError extends boolean = false>(options: Options<GetPlayerStatsData, ThrowOnError>) => (options.client ?? client).get<GetPlayerStatsResponses, unknown, ThrowOnError>({
    responseTransformer: getPlayerStatsResponseTransformer,
    url: '/api/players/{playerName}',
    ...options
});

/**
 * Get All Servers
 */
export const getAllServers = <ThrowOnError extends boolean = false>(options?: Options<GetAllServersData, ThrowOnError>) => (options?.client ?? client).get<GetAllServersResponses, unknown, ThrowOnError>({
    responseTransformer: getAllServersResponseTransformer,
    url: '/api/servers',
    ...options
});

/**
 * Refresh Server
 */
export const refreshServer = <ThrowOnError extends boolean = false>(options: Options<RefreshServerData, ThrowOnError>) => (options.client ?? client).put<RefreshServerResponses, RefreshServerErrors, ThrowOnError>({
    url: '/api/servers/heartbeat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Server Info
 */
export const getServerInfo = <ThrowOnError extends boolean = false>(options: Options<GetServerInfoData, ThrowOnError>) => (options.client ?? client).get<GetServerInfoResponses, unknown, ThrowOnError>({ url: '/api/servers/{id}/info', ...options });
