// This file is auto-generated by @hey-api/openapi-ts

import type { GetAllServersResponse, GetPlayerStatsResponse } from './types.gen';

const playerStatsResponseSchemaResponseTransformer = (data: any) => {
    data.playtimeSeconds = BigInt(data.playtimeSeconds.toString());
    return data;
};

export const getPlayerStatsResponseTransformer = async (data: any): Promise<GetPlayerStatsResponse> => {
    data = playerStatsResponseSchemaResponseTransformer(data);
    return data;
};

const serverResponseSchemaResponseTransformer = (data: any) => {
    data.id = BigInt(data.id.toString());
    return data;
};

export const getAllServersResponseTransformer = async (data: any): Promise<GetAllServersResponse> => {
    data = data.map((item: any) => serverResponseSchemaResponseTransformer(item));
    return data;
};
