/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq;


import com.q3js.jooq.tables.Events;
import com.q3js.jooq.tables.Servers;
import com.q3js.jooq.tables.records.EventsRecord;
import com.q3js.jooq.tables.records.ServersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventsRecord> EVENTS_PKEY1 = Internal.createUniqueKey(Events.EVENTS, DSL.name("events_pkey1"), new TableField[] { Events.EVENTS.ID }, true);
    public static final UniqueKey<ServersRecord> SERVERS_PKEY = Internal.createUniqueKey(Servers.SERVERS, DSL.name("servers_pkey"), new TableField[] { Servers.SERVERS.ID }, true);
    public static final UniqueKey<ServersRecord> UK_SERVERS_HOST_PROXY_TARGET = Internal.createUniqueKey(Servers.SERVERS, DSL.name("uk_servers_host_proxy_target"), new TableField[] { Servers.SERVERS.HOST, Servers.SERVERS.PROXY_PORT, Servers.SERVERS.TARGET_PORT }, true);
}
