quarkus:
  http:
    cors:
      enabled: true
      origins: "http://localhost:3000,https://q3js.com"
      methods: "GET,PUT,POST,DELETE,OPTIONS"
      headers: "origin,accept,authorization,content-type,x-requested-with"
      access-control-allow-credentials: true

q3js:
  server-info:
    timeout-ms: 3000
    scheme: http
